# Generated by Django 4.1.4 on 2023-01-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('trade_name', models.CharField(blank=True, max_length=100, null=True)),
                ('trade_description', models.TextField(blank=True, max_length=5000, null=True)),
                ('trade_image', models.ImageField(upload_to='product/')),
            ],
        ),
    ]
