# Generated by Django 4.1.4 on 2023-01-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacioni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('contact_textarea', models.TextField(blank=True, max_length=5000, null=True)),
                ('contact_number', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
